const ZOOM_CANVAS_SIZE = 200;
const ZOOM_CANVAS_AREA = 10;
const ZOOM_CANVAS_GRID_SIZE = 3;
const ZOOM_CANVAS_OFFSET = { x: 50, y: -100 };

export {
	ZOOM_CANVAS_SIZE,
	ZOOM_CANVAS_AREA,
	ZOOM_CANVAS_GRID_SIZE,
	ZOOM_CANVAS_OFFSET,
};
